//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Querying.Referrals.Services.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegalReferredInOutCustomer
    {
        public int ReferredInOutId { get; set; }
        public int CustomerId { get; set; }
        public int ReferralId { get; set; }
        public int ProductId { get; set; }
        public bool InOut { get; set; }
        public Nullable<int> SecondCustomerId { get; set; }
    }
}
