//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Querying.Referrals.Services.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegalCustomerHistory
    {
        public int logID { get; set; }
        public int customerID { get; set; }
        public string logText { get; set; }
        public Nullable<int> logLevel { get; set; }
        public string loggedBy { get; set; }
        public System.DateTime logtime { get; set; }
        public bool important { get; set; }
        public Nullable<byte> PlanningAheadTypeId { get; set; }
    }
}
