//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Querying.Referrals.Services.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referral
    {
        public int ReferralId { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> SourceCompanyId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string CustomerForeName { get; set; }
        public string CustomerSurName { get; set; }
        public Nullable<System.DateTime> CustomerDob { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerCity { get; set; }
        public string CustomerStateProvince { get; set; }
        public string CustomerPostalCode { get; set; }
        public Nullable<int> CustomerCountryId { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerTelephoneNumber { get; set; }
        public string CustomerMobileNumber { get; set; }
        public Nullable<int> SecondCustomerId { get; set; }
        public string SecondCustomerForeName { get; set; }
        public string SecondCustomerSurName { get; set; }
        public Nullable<System.DateTime> SecondCustomerDob { get; set; }
        public string SecondCustomerAddress { get; set; }
        public string SecondCustomerCity { get; set; }
        public string SecondCustomerStateProvince { get; set; }
        public string SecondCustomerPostalCode { get; set; }
        public Nullable<int> SecondCustomerCountryId { get; set; }
        public string SecondCustomerEmail { get; set; }
        public string SecondCustomerTelephoneNumber { get; set; }
        public string SecondCustomerMobileNumber { get; set; }
        public Nullable<int> ProductEventId { get; set; }
    }
}
